import unittest
from unittest.mock import Mock, patch
from pieces_os_client.models.annotation import Annotation
from pieces_os_client.models.annotation_type_enum import AnnotationTypeEnum
from pieces_os_client.models.seeded_annotation import SeededAnnotation
from pieces_os_client.wrapper.basic_identifier.annotation import BasicAnnotation
