# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist
from pieces_os_client.models.auth0_identity import Auth0Identity
from pieces_os_client.models.auth0_user_metadata import Auth0UserMetadata

class Auth0User(BaseModel):
    """
      # noqa: E501
    """
    blocked_for: Optional[conlist(StrictStr)] = None
    created_at: Optional[datetime] = None
    email: Optional[StrictStr] = None
    email_verified: Optional[StrictBool] = Field(default=None, description="Indicates whether the user has verified their email address. Mapped from email_verified -> emailVerified.")
    family_name: Optional[StrictStr] = Field(default=None, description="User's family name.")
    given_name: Optional[StrictStr] = Field(default=None, description="User's given name. ")
    guardian_authenticators: Optional[conlist(StrictStr)] = None
    identities: Optional[conlist(Auth0Identity)] = Field(default=None, description="Contains info retrieved from the identity provider with which the user originally authenticates.")
    last_ip: Optional[StrictStr] = None
    last_login: Optional[datetime] = None
    locale: Optional[StrictStr] = None
    logins_count: Optional[StrictInt] = None
    name: Optional[StrictStr] = Field(default=None, description=" User's full name.")
    nickname: Optional[StrictStr] = Field(default=None, description="User's nickname. ")
    picture: Optional[StrictStr] = Field(default=None, description="mapped from picture.URL pointing to the user's profile picture. ")
    updated_at: Optional[datetime] = None
    user_id: Optional[StrictStr] = None
    user_metadata: Optional[Auth0UserMetadata] = None
    username: Optional[StrictStr] = Field(default=None, description=" (unique) User's username.  ")
    __properties = ["blocked_for", "created_at", "email", "email_verified", "family_name", "given_name", "guardian_authenticators", "identities", "last_ip", "last_login", "locale", "logins_count", "name", "nickname", "picture", "updated_at", "user_id", "user_metadata", "username"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Auth0User:
        """Create an instance of Auth0User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in identities (list)
        _items = []
        if self.identities:
            for _item in self.identities:
                if _item:
                    _items.append(_item.to_dict())
            _dict['identities'] = _items
        # override the default output from pydantic by calling `to_dict()` of user_metadata
        if self.user_metadata:
            _dict['user_metadata'] = self.user_metadata.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Auth0User:
        """Create an instance of Auth0User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Auth0User.parse_obj(obj)

        _obj = Auth0User.parse_obj({
            "blocked_for": obj.get("blocked_for"),
            "created_at": obj.get("created_at"),
            "email": obj.get("email"),
            "email_verified": obj.get("email_verified"),
            "family_name": obj.get("family_name"),
            "given_name": obj.get("given_name"),
            "guardian_authenticators": obj.get("guardian_authenticators"),
            "identities": [Auth0Identity.from_dict(_item) for _item in obj.get("identities")] if obj.get("identities") is not None else None,
            "last_ip": obj.get("last_ip"),
            "last_login": obj.get("last_login"),
            "locale": obj.get("locale"),
            "logins_count": obj.get("logins_count"),
            "name": obj.get("name"),
            "nickname": obj.get("nickname"),
            "picture": obj.get("picture"),
            "updated_at": obj.get("updated_at"),
            "user_id": obj.get("user_id"),
            "user_metadata": Auth0UserMetadata.from_dict(obj.get("user_metadata")) if obj.get("user_metadata") is not None else None,
            "username": obj.get("username")
        })
        return _obj


