# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from pieces_os_client.models.embedded_model_schema import EmbeddedModelSchema
from pieces_os_client.models.migration_status_enum import MigrationStatusEnum
from typing import Optional, Set
from typing_extensions import Self

class MigrationProgress(BaseModel):
    """
    This is a model used to communicate the status of a migration in progress
    """ # noqa: E501
    var_schema: Optional[EmbeddedModelSchema] = Field(default=None, alias="schema")
    total_items: StrictInt = Field(alias="totalItems")
    processed_items: StrictInt = Field(alias="processedItems")
    current_batch: StrictInt = Field(alias="currentBatch")
    batch_size: StrictInt = Field(alias="batchSize")
    percent_complete: Union[StrictFloat, StrictInt] = Field(alias="percentComplete")
    elapsed_milliseconds: StrictInt = Field(alias="elapsedMilliseconds")
    current_stage: StrictStr = Field(alias="currentStage")
    readable: StrictStr
    estimated_time_remaining: Optional[StrictInt] = Field(default=None, alias="estimatedTimeRemaining")
    status: MigrationStatusEnum
    __properties: ClassVar[List[str]] = ["schema", "totalItems", "processedItems", "currentBatch", "batchSize", "percentComplete", "elapsedMilliseconds", "currentStage", "readable", "estimatedTimeRemaining", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MigrationProgress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MigrationProgress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schema": EmbeddedModelSchema.from_dict(obj["schema"]) if obj.get("schema") is not None else None,
            "totalItems": obj.get("totalItems"),
            "processedItems": obj.get("processedItems"),
            "currentBatch": obj.get("currentBatch"),
            "batchSize": obj.get("batchSize"),
            "percentComplete": obj.get("percentComplete"),
            "elapsedMilliseconds": obj.get("elapsedMilliseconds"),
            "currentStage": obj.get("currentStage"),
            "readable": obj.get("readable"),
            "estimatedTimeRemaining": obj.get("estimatedTimeRemaining"),
            "status": obj.get("status")
        })
        return _obj


