# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr
from pieces_os_client.models.byte_descriptor import ByteDescriptor
from pieces_os_client.models.embedded_model_schema import EmbeddedModelSchema

class VerifiedOSFilesystemPath(BaseModel):
    """
    This will return is the given path was verified/ or it was invalid.  and if it is valid if it is a file/folder  note: file/directory are both null.  # noqa: E501
    """
    bytes: Optional[ByteDescriptor] = None
    denied: Optional[StrictBool] = Field(default=None, description="This means that attempting to access the file was not aloud(ie no permission)")
    directory: Optional[StrictBool] = None
    file: Optional[StrictBool] = None
    path: StrictStr = Field(...)
    var_schema: Optional[EmbeddedModelSchema] = Field(default=None, alias="schema")
    verified: StrictBool = Field(default=..., description="This means if the path(file/folder) exists on the machine.")
    __properties = ["bytes", "denied", "directory", "file", "path", "schema", "verified"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VerifiedOSFilesystemPath:
        """Create an instance of VerifiedOSFilesystemPath from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of bytes
        if self.bytes:
            _dict['bytes'] = self.bytes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VerifiedOSFilesystemPath:
        """Create an instance of VerifiedOSFilesystemPath from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VerifiedOSFilesystemPath.parse_obj(obj)

        _obj = VerifiedOSFilesystemPath.parse_obj({
            "bytes": ByteDescriptor.from_dict(obj.get("bytes")) if obj.get("bytes") is not None else None,
            "denied": obj.get("denied"),
            "directory": obj.get("directory"),
            "file": obj.get("file"),
            "path": obj.get("path"),
            "var_schema": EmbeddedModelSchema.from_dict(obj.get("schema")) if obj.get("schema") is not None else None,
            "verified": obj.get("verified")
        })
        return _obj


