# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool

class WorkstreamSuggestionType(BaseModel):
    """
    This is used to map the types of the iterable to given booleans of their respective material types  # noqa: E501
    """
    anchor: Optional[StrictBool] = None
    anchors: Optional[StrictBool] = None
    asset: Optional[StrictBool] = None
    assets: Optional[StrictBool] = None
    conversation: Optional[StrictBool] = None
    conversations: Optional[StrictBool] = None
    person: Optional[StrictBool] = None
    persons: Optional[StrictBool] = None
    var_schema: Optional[StrictBool] = Field(default=None, alias="schema")
    seed: Optional[StrictBool] = None
    seeds: Optional[StrictBool] = None
    summaries: Optional[StrictBool] = None
    summary: Optional[StrictBool] = None
    tag: Optional[StrictBool] = None
    tags: Optional[StrictBool] = None
    website: Optional[StrictBool] = None
    websites: Optional[StrictBool] = None
    __properties = ["anchor", "anchors", "asset", "assets", "conversation", "conversations", "person", "persons", "schema", "seed", "seeds", "summaries", "summary", "tag", "tags", "website", "websites"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkstreamSuggestionType:
        """Create an instance of WorkstreamSuggestionType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkstreamSuggestionType:
        """Create an instance of WorkstreamSuggestionType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkstreamSuggestionType.parse_obj(obj)

        _obj = WorkstreamSuggestionType.parse_obj({
            "anchor": obj.get("anchor"),
            "anchors": obj.get("anchors"),
            "asset": obj.get("asset"),
            "assets": obj.get("assets"),
            "conversation": obj.get("conversation"),
            "conversations": obj.get("conversations"),
            "person": obj.get("person"),
            "persons": obj.get("persons"),
            "var_schema": obj.get("schema"),
            "seed": obj.get("seed"),
            "seeds": obj.get("seeds"),
            "summaries": obj.get("summaries"),
            "summary": obj.get("summary"),
            "tag": obj.get("tag"),
            "tags": obj.get("tags"),
            "website": obj.get("website"),
            "websites": obj.get("websites")
        })
        return _obj


